#encoding: utf-8

ipaddr1 = IPAddr.new "127.0.0.1/24"
user_list = [
["-65179155@twitter.com", "$2a$10$WHRV8LhbRt19YPFysqqN0uDLCjeFh2dgzeDsAW5AthKtv5DmgQ4v6", nil, nil, nil, 1, "2014-11-08 17:26:10", "2014-11-08 17:26:10", ipaddr1, ipaddr1,"Lau Garcia Casadiego", false], 
["lauragarcia1993@hotmail.com", "$2a$10$DouvJr5ACwq1qufdrVZDQuZcjzLWlhgwszYr5IOaT.HJBwS0U2BC.", nil, nil, nil, 4, "2014-11-08 17:27:08", "2014-11-08 17:26:37", ipaddr1, ipaddr1, "Laura Garcia Casadiego", false],
["admin@uninorte.edu.co", "$2a$10$1FJ1jcFl4UsFEhXNympQa.bLLgjC.XY6iLBfVpajD9seWe/fCLOoi", nil, nil, nil, 3, "2014-10-10 22:06:41", "2014-10-10 01:44:54", ipaddr1, ipaddr1, "Admin", true], 
["hatch.heart@gmail.com", "$2a$10$r8YW87TLRBMS07YcnmsdJeK4SVZrIaUAOkrFb5/wZdLa7DQBJoEte", nil, nil, nil, 2, "2014-11-04 02:51:01", "2014-10-09 23:05:37", ipaddr1, ipaddr1, "Rubiel Velasquez", false],
["asdf-30373277@twitter.com", "$2a$10$aAr48mXt7ynaTShdfZtoDexP2vlZhBrhiavYBIweZXiqy.PL7uz8y", nil, nil, nil, 1, "2014-11-04 03:20:56", "2014-11-04 03:20:56", ipaddr1, ipaddr1, "Demo", false],
["change@me-736015896-twitter.com", "$2a$10$DenR7OP0mnUT7frMwswWru6zOlaLz4306sjFf2GhK1xxu3DBA2l7u", nil, nil, nil, 8, "2014-11-08 18:01:20", "2014-11-08 17:54:39", ipaddr1, ipaddr1, "r ", false]
]
user_list.each do |email, encrypted_password, reset_password_token, reset_password_sent_at, remember_created_at, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip, name, admin|
  User.create( email: email, encrypted_password: encrypted_password, reset_password_token: reset_password_token, reset_password_sent_at: reset_password_sent_at, remember_created_at: remember_created_at, sign_in_count: sign_in_count, current_sign_in_at: current_sign_in_at, last_sign_in_at: last_sign_in_at, current_sign_in_ip: current_sign_in_ip, last_sign_in_ip: last_sign_in_ip, name: name, admin: admin )
end


publications_list = [
 [ "Erase un principito que no quería estudiar. Cierta noche, después de haber recibido una buena regañina por su pereza, suspiro tristemente, diciendo:",'',1,1,true],
 [ "¡Ay! ¿Cuándo seré mayor para hacer lo que me apetezca? Y he aquí que, a la mañana siguiente, descubrió sobre su cama una bobina de hilo de oro de la que salió una débil voz: Trátame con cuidado, príncipe.",'',2,1,true],
 [ "Este hilo representa tus días. Conforme vayan pasando, el hilo se ira soltando. Sé que deseas crecer pronto... Pues bien, te concedo el don de desenrollar el hilo a tu antojo, pero todo aquello que hayas desenrollado no podrás ovillarlo.",'',1,1,true],
 [ "El príncipe, para cerciorarse, tiro con ímpetu del hilo y se encontró convertido en un apuesto príncipe. Tiro un poco mas y se vio llevando la corona de su padre. ¡Era rey! Con un nuevo tironcito, dijo:Bobina ¿Cómo serán mi esposa e hijos?",'',2,1,true],
 [ "En el mismo instante, una bellísima joven, y cuatro niños rubios surgieron a su lado. Sin pararse a pensar, su curiosidad se iba apoderando de él y siguió soltando mas hilo para saber como serian sus hijos de mayores.",'',1,1,false],
 [ "De pronto se miro al espejo y vio la imagen de un anciano decrépito, de escasos cabellos nevados. Se asusto del poco hilo que quedaba en la bobina. ¡Los instantes de su vida estaban contados! rapidamente, intento enrollarlo, pero sin lograrlo.",'',2,1,true],
 [ "Has desperdiciado tontamente tu existencia. Ahora ya sabes que los días perdidos no pueden recuperarse. Has sido un perezoso al pretender pasar por la vida sin molestarte en hacer el trabajo de todos los días. Sufre, pues tu castigo.",'',1,1,false],
 [ "El rey, tras un grito de pánico, cayó muerto: había consumido la existencia sin hacer nada de provecho.",'',2,1,true],
 [ "Había dejado de nevar y los niños, ansiosos de libertad, salieron de casa y empezaron a corretear por la blanca y mullida alfombra recién formada.",'',2,1,true],
 [ "La hija del herrero, tomando puñados de nieve con sus manitas hábiles, se entrego a la tarea de moldearla. Haré un muñeco como el hermanito que hubiera deseado tener se dijo.",'',1,1,true],
 [ "Le salio un niñito precioso, redondo, con ojos de carbón y un botón rojo por boca. La pequeña estaba entusiasmada con su obra y convirtió al muñeco en su inseparable compañero durante los tristes días de aquel invierno. Le hablaba, le mimaba...",'',2,1,false],
 [ "Pero pronto los días empezaron a ser mas largos y los rayos de sol mas calidos... El muñeco se fundió sin dejar mas rastro de su existencia que un charquito con dos carbones y un botón rojo. La niña lloro con desconsuelo.",'',1,1,true],
 ["Un viejecito, que buscaba en el sol tibieza para su invierno, le dijo dulcemente: Seca tus lagrimas, bonita, por que acabas de recibir una gran lección: ahora ya sabes que no debe ponerse el corazón en cosas perecederas.",'',2,1,false],
 ["",'<iframe class="vine-embed" src="https://vine.co/v/M7MFlunmLJ5/embed/simple" width="600" height="600" frameborder="0"></iframe><script async src="//platform.vine.co/static/scripts/embed.js" charset="utf-8"></script>',1,3,false],
 ["",'<iframe class="vine-embed" src="https://vine.co/v/hlvnwTLrqvw/embed/simple" width="600" height="600" frameborder="0"></iframe><script async src="//platform.vine.co/static/scripts/embed.js" charset="utf-8"></script>',2,3,true],
 ["",'<iframe class="vine-embed" src="https://vine.co/v/OeEvtlHQhKY/embed/simple" width="600" height="600" frameborder="0"></iframe><script async src="//platform.vine.co/static/scripts/embed.js" charset="utf-8"></script>',2,3,true],
 ["",'<iframe class="vine-embed" src="https://vine.co/v/OeE99bhiubi/embed/simple" width="600" height="600" frameborder="0"></iframe><script async src="//platform.vine.co/static/scripts/embed.js" charset="utf-8"></script>',1,3,false],
 ["",'<iframe class="vine-embed" src="https://vine.co/v/OeEQ9xdz7r2/embed/simple" width="600" height="600" frameborder="0"></iframe><script async src="//platform.vine.co/static/scripts/embed.js" charset="utf-8"></script>',2,3,true],
["",'<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/vJBX1kCJwp/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_top">#CARTAGENA #NIIF</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A photo posted by Esteban (@estebamier) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2014-11-08T13:47:42+00:00">Nov 11, 2014 at 5:47am PST</time></p></div></blockquote><script async defer src="//platform.instagram.com/en_US/embeds.js"></script>',1,2,false],
["",'<blockquote class="instagram-media" data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div><p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;"><a href="https://instagram.com/p/vJVytXq1JD/" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" target="_top">A photo posted by Jil (@jillyfish_)</a> on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2014-11-08T16:46:08+00:00">Nov 11, 2014 at 8:46am PST</time></p></div></blockquote><script async defer src="//platform.instagram.com/en_US/embeds.js"></script>',1,2,false],
["",'<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/vJm3_nujcW/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_top">Breakfast drink  berry mix *^* whoops we have evening</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">Ein von Sabrina ~ (@schoko_junji) gepostetes Foto on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2014-11-08T19:15:24+00:00">Nov 11, 2014 at 11:15 PST</time></p></div></blockquote><script async defer src="//platform.instagram.com/en_US/embeds.js"></script>',2,2,false],
["",'<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/vJj-papiPg/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_top">2011년인가 #애기다</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">Una foto pubblicata da $U JIN♥ WAFFLE (@bbang_su) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2014-11-08T18:50:06+00:00">Nov 11, 2014 at 10:50 PST</time></p></div></blockquote><script async defer src="//platform.instagram.com/en_US/embeds.js"></script>',2,2,false],
["",'<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/vJkWjwok2B/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_top">너 손 너무 대충한다💀 #퍼그 #둥블리</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A video posted by 🐰 (@cemonne) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2014-11-08T18:53:22+00:00">Nov 11, 2014 at 10:53am PST</time></p></div></blockquote><script async defer src="//platform.instagram.com/en_US/embeds.js"></script>',1,2,false],
["",'<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/vJR9zuMTbN/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_top">SHOP KILLSTAR.com | WE SHIP WORLDWIDE 🌙</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">Una foto publicada por KILLSTAR Co. (@killstarco) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2014-11-08T16:12:42+00:00">Nov 11, 2014 at 8:12 PST</time></p></div></blockquote><script async defer src="//platform.instagram.com/en_US/embeds.js"></script>',1,2,false],
["",'<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/vJPPAJFwD8/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_top">윙크쟁이</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A video posted by 태은이 숑 (@raniatae) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2014-11-08T15:48:50+00:00">Nov 11, 2014 at 7:48am PST</time></p></div></blockquote><script async defer src="//platform.instagram.com/en_US/embeds.js"></script>',2,2,false],
["",'<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/vJmQSHNtDr/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_top">No se pueden quejar !!!! Para mis instafriends que me pidieron rutina de glúteos hoy le di durooooo y me la pase filmando 😂😂 ahí como pude porque no tengo quien me grabe pero espero que les guste!! Me faltaban estos dos que son excelentes , matadores, aceleradores, quemadores y demás jajja . Prueben y me dicen que tal. 3 series de cada uno de 15 a 20 repeticiones. El ejercicio de la derecha se puede hacer sin bosu 👌 . Todo esto mañana me va a doler 🔥🔥🔥🔥🔥🔥🔥🔥 #booty #squats #sisepuede #sinfiltro #sinexcusas #nomasexcusas #glutes #fitbody #fitgirl #lifestyle #gymfreak #gymtime #rutina #gluteos #abs #bodytech #vamospormas</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A video posted by Laura Piedrahita Gomez (@laupiedrahitag) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2014-11-08T19:09:59+00:00">Nov 11, 2014 at 11:09am PST</time></p></div></blockquote><script async defer src="//platform.instagram.com/en_US/embeds.js"></script>',2,2,false],
["",'<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/vJnZdnoh-y/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_top">Comiendo saludable !! No hay excusas para comer saludable !! Fundacion Mario SantoDomingo !! La cajita feliz para todos 💚👏.... Siempre brindando los mejores servicios en alimentación saludable 👏👏👏</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A photo posted by Fitness Food Gourmet (@fitnessfoodgourmet) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2014-11-08T19:19:58+00:00">Nov 11, 2014 at 11:19am PST</time></p></div></blockquote><script async defer src="//platform.instagram.com/en_US/embeds.js"></script>',1,2,false],
["",'<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/vJo3qdtN8e/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_top">Amigos inmaduros...😂😂😂👌 @luisafernandaw @luisafernandaw @luisafernandaw La Reina del Instagram 💃🎉🎉🎉</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">Un vídeo publicado por #Que Boleta!😂👌💛💛💙❤️ Fun! (@queboletaoficial) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2014-11-08T19:32:50+00:00">Nov 11, 2014 at 11:32 PST</time></p></div></blockquote><script async defer src="//platform.instagram.com/en_US/embeds.js"></script>',1,2,false],
["",'<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/vJuS8RP7h-/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_top">DISPONIBLE LOS MEJORES PUDINES DE HARINA DE ALMENDRAS Y SPLENDA, IDEALES PARA PERSONAS DIABÉTICAS O BAJO REGÍMENES ALIMENTICIOS SIN REMORDIMIENTOS Y SIN PECADOS. DOMICILIOS AL 3116335</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A photo posted by Saludable Factory (@saludablefactory) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2014-11-08T20:20:15+00:00">Nov 11, 2014 at 12:20pm PST</time></p></div></blockquote><script async defer src="//platform.instagram.com/en_US/embeds.js"></script>',2,2,false],
["",'<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/vJx5dQlvLm/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_top">Que será que veo?!!! Mejor me arreglo y me voy a caminar con mi mami ...💪👍💙 #GuapitoLeyva</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">Una foto publicada por VALENTINA LIZCANO (@valelizcano) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2014-11-08T20:51:43+00:00">Nov 11, 2014 at 12:51 PST</time></p></div></blockquote><script async defer src="//platform.instagram.com/en_US/embeds.js"></script>',1,2,false],
["",'<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/puw8sOpBR-/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_top">Mas te vale q eso sea de chitoo hahahahah</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A video posted by Laura Garcia (@laucasadiego) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2014-06-27T02:26:58+00:00">Jun 6, 2014 at 7:26pm PDT</time></p></div></blockquote><script async defer src="//platform.instagram.com/en_US/embeds.js"></script>',2,2,false],
["",'<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/s5TzWzpBRr/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_top">Bazurtooo @trucupeydisco</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A video posted by Laura Garcia (@laucasadiego) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2014-09-13T18:18:07+00:00">Sep 9, 2014 at 11:18am PDT</time></p></div></blockquote><script async defer src="//platform.instagram.com/en_US/embeds.js"></script>',2,2,false],
["",'<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/o1oAe8JBcu/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_top">#Felicidad</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A photo posted by Laura Garcia (@laucasadiego) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2014-06-04T21:52:08+00:00">Jun 6, 2014 at 2:52pm PDT</time></p></div></blockquote><script async defer src="//platform.instagram.com/en_US/embeds.js"></script>',2,2,false],
["",'<blockquote class="instagram-media" data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div><p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;"><a href="https://instagram.com/p/vKb6MVBOOB/" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" target="_top">A photo posted by Estraterrestre Sesy (@estraterrestresesypr)</a> on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2014-11-09T02:58:49+00:00">Nov 11, 2014 at 6:58pm PST</time></p></div></blockquote><script async defer src="//platform.instagram.com/en_US/embeds.js"></script>',2,2,false],
[ "Erase una vez un cedro satisfecho de su hermosura.",'',1,1,true],
[ "Plantado en mitad del jardín, superaba en altura a todos los demás árboles. Tan bellamente dispuestas estaban sus ramas, que parecía un gigantesco candelabro. Si con lo hermoso que soy diera fruto, se dijo, ningún árbol podría compararse conmigo.",'',2,1,false],
[ "Y decidió observar a los otros árboles y hacer lo mismo con ellos. Por fin, en lo alto de su erguida copa, apunto un bellísimo fruto. Tendré que alimentarlo bien para que crezca mucho, se dijo.",'',1,1,false],
[ "Tanto y tanto creció aquel fruto, que se hizo demasiado grande. La copa del cedro, no pudiendo sostenerlo, se fue doblando; y cuando el fruto maduro, la copa, que era el orgullo y la gloria del árbol, empezó a tambalearse hasta que se troncho.",'',2,1,false],
[ " ¡A cuantos hombres, como el cedro, su demasiada ambición les arruina!",'',1,1,false],
[ "Erase un príncipe muy admirado en su reino. Todas las jóvenes casaderas deseaban tenerle por esposo. Pero el no se fijaba en ninguna y pasaba su tiempo jugando con Zapaquilda, una preciosa gatita, junto a las llamas del hogar.",'',2,1,true],
[ "Un día, dijo en voz alta: Eres tan cariñosa y adorable que, si fueras mujer, me casaría contigo. En el mismo instante apareció en la estancia el Hada de los Imposibles, que dijo: Príncipe tus deseos se han cumplido",'',1,1,false],
[ "El joven, deslumbrado, descubrió junto a el a Zapaquilda, convertida en una bellísima muchacha.",'',2,1,false],
[ "Al día siguiente se celebraban las bodas y todos los nobles y pobres del reino que acudieron al banquete se extasiaron ante la hermosa novia. De pronto, vieron a la joven lanzarse sobre un ratoncillo que estaba por el salón y zampárselo al atraparlo.",'',2,1,false],
[ "El príncipe llamó al Hada de los Imposibles para que convirtiera a su esposa en la gatita que había sido. Pero el Hada no acudió, y nadie nos ha contado si tuvo que pasarse la vida contemplando como su esposa daba cuenta de los ratones.",'',1,1,false],
[ "Su extraordinario coraje la salvó a ella y salvó a sus pequeñuelos. Porque nada hay imposible cuando el amor guía las acciones.",'',2,1,true],
[ "Pero ya era demasiado tarde: los cazadores estaban ante ella, dispuestos a herirla.",'',1,1,false]

]

publications_list.each do |content, url , user_id, type, singularity|
  Publication.create(content: content, url: url, user_id: user_id, type: type, singularity: singularity)
end

histories_list = [
	[1, "La Bobina Maravillosa"],[9,"El Muñeco de Nieve"],[34,"El Cedro Vanidoso"],
	[39,"La Gata Encantanda"], [2,"La sepultura del Lobo"], [3,"El Papel y la tinta"], [4,"El nuevo Amigo"],
	[6,"El honrado leñador"], [8,"El caballo amaestrado"], [10, "La ratita blanca"], [12, "Nuez de Oro"],
	[14, "La Ostra y el Cangrejo"], [15, "Caperucita y las Aves"],[16,"El granjero bondadoso"], 
	[17,"La aventura del agua"],[44,"El camino peligroso"],[18, "El viajero extraviado"]
]

histories_list.each do | publication_id, title|
	History.create(publication_id: publication_id, title: title)
end

h_and_p_list = [
	[1,nil,2,1],  [1,1,3,2],[1,2,4,3],[1,3,5,4],[1,4,6,5],[1,5,7,6],[1,6,8,7],[1,7,nil,8],
	[2,nil,10,9], [2,9,11,10],[2,10,12,11],[2,11,13,12],[2,12,nil,13],
	[3,nil,35,34],[3,34,36,35],[3,35,37,36],[3,36,38,37],[3,37,nil,38],
	[4,nil,40,39],[4,39,41,40],[4,40,42,41],[4,41,43,42],[4,42,nil,43],
	[5,nil,20,2], [5,2,21,20],[5,20,22,21],[5,21,23,22],[5,22,nil,23],
	[6,nil,25,3], [6,3,26,25],[6,25,27,26],[6,26,29,27],[6,27,nil,29],
	[7,nil,30,4], [7,4,31,30],[7,30,32,31],[7,31,5,32],[7,32,nil,5],
	[8,nil,30,6], [8,6,7,30],[8,30,13,7],[8,7,32,13],[8,13,nil,32],
	[9,nil,24,8], [9,8,22,24],[9,24,30,22],[9,22,16,30],[9,30,nil,16],
	[10,nil,33,10],[10,10,23,33],[10,33,7,23],[10,23,nil,7],
	[11,nil,31,12],[11,12,22,31],[11,31,5,22],[11,22,nil,5],
	[12,nil,13,14],[12,14,31,13],[12,13,nil,31],
	[13,nil,5,15],[13,15,7,5],[13,5,11,7],[13,7,13,11],[13,11,18,13],[13,13,nil,18],
	[14,nil,7,16],[14,16,20,7],[14,5,7,20],[14,20,nil,5],
	[15,nil,19,17],[15,17,21,19],[15,19,24,21],[15,21,28,24],[15,24,nil,28],
	[16,nil,13,44],[16,44,16,13],[16,13,18,16],[16,16,19,18],[16,18,nil,19],
	[17,nil,44,18],[17,18,35,44],[17,44,40,35],[17,35,3,40],[17,40,nil,3]
]
h_and_p_list.each do |history_id, llink_id, rlink_id, publication_id|
	PublicationsAndHistory.create(history_id: history_id, llink_id: llink_id, rlink_id: rlink_id, publication_id: publication_id)	
end






